name: Github Action Demo

on: [push]

jobs:
  echo_hello_wordls:
    runs-on: ubuntu-latest
    steps:
      - name: "挨拶"
        run: echo "Nice to meet you!!"
  echo_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "別れの挨拶をする"
        run: echo "Good Bye!!"
